In [6]:
import numpy as np
from sklearn.datasets import load_boston

In [7]:
boston = load_boston()
x = boston['data']
y = boston['target']

In [11]:
from sklearn.model_selection import train_test_split

In [33]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.8)

In [34]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(x_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [35]:
model.intercept_

11.326423264644628

In [36]:
model.coef_

array([-2.58397913e-01,  3.94521263e-02,  1.01475795e-01,  4.59967954e-01,
       -1.54534968e+01,  5.94808287e+00, -1.24232364e-02, -9.11382844e-01,
        2.99721339e-01, -1.07638730e-02, -6.55157632e-01,  1.11815922e-02,
       -3.74532177e-01])

In [37]:
model.predict(x_test)

array([ 33.42726136,  29.80810653,  20.01924712,  28.74779641,
        24.47755315,  17.74348296,  27.01214665,  15.29303021,
         3.5436155 ,  22.17180213,   8.10070219,  19.43205404,
        28.22164755,  36.35503482,  35.22229484,  13.32950367,
        31.94387371,  28.09627612,  28.31370201,  23.29365248,
        25.16685601,  29.56189289,  35.39547541,  14.50375356,
        21.87194732,   3.14437085,  24.48945436,  41.33964393,
        10.88149975,  43.99278193,  21.06670472,  37.27407927,
        12.48021959,  22.90188488,  21.77589777,  12.35166072,
        25.16775912,  18.73484255,  23.50077485,  14.28658557,
        23.38810826,  19.62674335,  15.72216699,  18.33963805,
        26.97337807,  17.67380439,  33.26642883,  17.67910632,
        10.67332216,  16.26404747,  19.57356922,  10.30511402,
        13.34988462,  20.0838266 ,  34.50480663,  29.25070947,
        30.28170191,  20.40029025,  23.84624252,  27.66877969,
        23.76100124,  40.23580103,  17.067379  ,  30.63

In [38]:
model.score(x_train,y_train)

0.7771670243152172

In [59]:
from sklearn.model_selection import cross_val_score
score = cross_val_score(model,x_test,y_test,cv = 5 ,scoring = 'r2')

In [60]:
avg_score = score.mean()

In [61]:
avg_score

0.7130024112399511

In [62]:
error = cross_val_score(model,x_test,y_test,cv = 15,scoring = 'neg_mean_squared_error')
error

array([-20.86471655, -16.67604771, -62.3419216 , -34.67775733,
       -29.43120066, -15.61570436, -22.20306472, -20.62997815,
       -20.31721315, -12.44472037, -47.50276182, -21.04904738,
       -16.69660988, -32.88624929, -11.45325766])

In [63]:
avg_error = error.mean()
avg_error

-25.65268337451632